modLoader="javafml" # Required - The mod loader, in this case Forge
loaderVersion="[28,)" # Required - The version range of the mod loader
license="MIT" # Required - The license of the mod

[[mods]]
modId="finclient" # Required - The mod id
version="${file.jarVersion}" # Required - The version of the mod
displayName="Finclient Mod" # Required - The display name of the mod
updateJSONURL="https://example.com/update.json" # Optional - URL for update information
displayURL="https://example.com" # Optional - URL for more information
logoFile="assets/finclient/logo.png" # Optional - Path to the mod logo

# Optional - Description of the mod
description='''
This is a Finclient mod for Minecraft.
'''

[[dependencies.finclient]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"